import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import BackgroundMap from "@/components/map/BackgroundMap";
import MapProvider from "@/components/map/MapProvider";
import "./globals.css";

// Preload local Space Grotesk fonts for faster paint
export const runtime = "edge";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="preload"
          href="/fonts/spacegrotesk/SpaceGrotesk-Regular.ttf"
          as="font"
          type="font/ttf"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href="/fonts/spacegrotesk/SpaceGrotesk-Medium.ttf"
          as="font"
          type="font/ttf"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href="/fonts/spacegrotesk/SpaceGrotesk-SemiBold.ttf"
          as="font"
          type="font/ttf"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href="/fonts/spacegrotesk/SpaceGrotesk-Bold.ttf"
          as="font"
          type="font/ttf"
          crossOrigin="anonymous"
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <MapProvider>
          <BackgroundMap />
          <div className="content-on-map">{children}</div>
        </MapProvider>
      </body>
    </html>
  );
}
