[project]
name = "shopping-automation"
version = "0.1.0"
description = "Multi-site grocery shopping automation with browser-use"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "browser-use>=0.9.0",
    "pydantic>=2.0.0",
    "fastapi>=0.100.0",
    "uvicorn>=0.20.0",
]
